//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by HMSSurgeryManager.rc
//
#define IDI_ICON                        0
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_HMSSurgeryManagTYPE         129
#define IDB_BMPREMINDER                 133
#define ID_FILE_SETUP                   32774
#define ID_FILE_REPORT                  32775
#define ID_FILE_CHANGEPASSWORD          32776
#define ID_SETUP_OPERATIONTYPE          32778
#define ID_SETUP_ANAESTHETICMETHOD      32779
#define ID_SETUP_ANESTHESIAMETHOD       32780
#define ID_FILE_STOCKINVENNTORY         32781
#define ID_REPORT_LISTOFPATIENTSURGERYREPORT 32782
#define ID_REPORT_DUTIESREPORT          32783
#define ID_SETUP_SURGERYTABLE           32784
#define ID_SETUP_HITECHOPERATION        32785
#define ID_REPORT_GENERALSURGERYREPORT  32786
#define ID_REPORT_THEUSEOFDRUGS         32787
#define ID_REPORT_THEUSEOFSYNTHETICDRUGS 32788
#define ID_REPORT_LISTOFPATIENTSUSINGPSYCHOTROPICDRUGS 32789
#define ID_REPORT_GENERALSURGERYOFTENREPORTED 32790
#define ID_GENERALSURGERYREPORT_GENERALSURGERYOFTENREPORTED 32791
#define ID_GENERALSURGERYREPORT_GENERALREPORTONHIGH 32792
#define ID_GENERALSURGERYREPORT_GENERALREPORTONMETHODSOFANESTHESIA 32793
#define ID_Menu                         32794
#define ID_REPORT_BAOCAOSUQUYETTOANVATTU 32795
#define ID_SETUP_APPLYDATE              32797
#define ID_REPORT_DRUGANDMATERIALSETTLEMENTREPORT 32798
#define ID_REPORT_SURGERYSCHEDULEREPORT 32799
#define ID_FILE_VIEWPARACLINICALINFORMATION 32800
#define ID_COMMAND_MEDICALCABINET       32801
#define ID_FILE_DRUGMATERIALORDERSHEET  32802
#define ID_FILE_RETURNDRUGORDERSHEET    32803
#define ID_REPORT_GENERALDEPARTMENTUSAGE 32804
#define ID_REPORT_DRUGMATERIALUNPICK    32805
#define ID_REPORT_DEBTMATERIAL          32806
#define ID_REPORT_SURGERYSCHEDULEALLREPORT 32807
#define ID_REPORT_DEBTMATERIALSUMMARY   32808
#define ID_FILE_STORAGEDETAIL           32809
#define ID_GENERALSURGERYREPORT_GENERALSURGERYOFTENREPORTEDNEW 32811
#define ID_FILE_SETUPPRESCRIPTIONLIST   32813
#define ID_SETTINGS_DOCTORINFO          32815
#define ID_REPORT_THEODOIVATTUPHONGMO   32816
#define ID_REPORT_LISTOFPATIENTSURGERYREPORT_V2 32818
#define ID_REPORT_BAOCAOPTTTTHUCHIENTAIB5 32819

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         32820
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
