#ifndef HMSWARDACCEPTANCE_H
#define HMSWARDACCEPTANCE_H
#include "GuiUtils.h"
#include "GuiView.h"
#include "DbField.h"
class CHMSWardAcceptance : public CGuiView{
protected:
public:
	CGuiLabel		m_wndInDateLabel;
	CGuiDateTimeCtrl	m_wndInDate;
	CGuiLabel		m_wndFromWardLabel;
	CGuiComboBox	m_wndFromWard;
	CGuiLabel		m_wndExamineDiseaseLabel;
	CGuiComboBox	m_wndExamineDisease;
	CGuiLabel		m_wndDepartmentDiseaseLabel;
	CGuiComboBox	m_wndDepartmentDisease;
	CGuiLabel		m_wndMainDiseaseLabel;
	CGuiComboBox	m_wndMainDisease;
	CGuiLabel		m_wndDiseaseAccompaniedLabel;
	CGuiComboBox	m_wndDiseaseAccompanied;
	CGuiLabel		m_wndRelationDiseaseLabel;
	CGuiTextCtrl	m_wndRelationDisease;
	CGuiLabel		m_wndReasonLabel;
	CGuiTextCtrl	m_wndReason;
	CGuiButton		m_wndUpdate;
	CGuiButton		m_wndSave;
	CGuiButton		m_wndCancel;
	CGuiLabel		m_wndInWardNoLabel;
	CGuiNumberCtrl	m_wndInWardNo;
	CGuiLabel		m_wndIntroducePlaceLabel;
	CGuiComboBox	m_wndIntroducePlace;
	CGuiLabel		m_wndTotalTimeLabel;
	CGuiNumberCtrl	m_wndTotalTime;
	CString	m_szInDate;
	CString	m_szFromWardKey;
	CString	m_szExamineDiseaseKey;
	CString	m_szDepartmentDiseaseKey;
	CString	m_szMainDiseaseKey;
	CString	m_szDiseaseAccompaniedKey;
	CString	m_szRelationDisease;
	CString	m_szReason;
	long	m_nInWardNo;
	CString	m_szIntroducePlaceKey;
	long	m_nTotalTime;
	//int			OnInDateChange(); 
	//int			OnInDateSetfocus(); 
	//int			OnInDateKillfocus(); 
	int			OnInDateCheckValue(); 
	int			OnFromWardSelectChange(int nOldItemSel, int nNewItemSel); 
	int			OnFromWardSelendok(); 
	//int			OnFromWardSetfocus(); 
	//int			OnFromWardKillfocus(); 
	int			OnFromWardLoadData(); 
	int			OnFromWardAddNew(); 
	int			OnExamineDiseaseSelectChange(int nOldItemSel, int nNewItemSel); 
	int			OnExamineDiseaseSelendok(); 
	//int			OnExamineDiseaseSetfocus(); 
	//int			OnExamineDiseaseKillfocus(); 
	int			OnExamineDiseaseLoadData(); 
	int			OnExamineDiseaseAddNew(); 
	int			OnDepartmentDiseaseSelectChange(int nOldItemSel, int nNewItemSel); 
	int			OnDepartmentDiseaseSelendok(); 
	//int			OnDepartmentDiseaseSetfocus(); 
	//int			OnDepartmentDiseaseKillfocus(); 
	int			OnDepartmentDiseaseLoadData(); 
	int			OnDepartmentDiseaseAddNew(); 
	int			OnMainDiseaseSelectChange(int nOldItemSel, int nNewItemSel); 
	int			OnMainDiseaseSelendok(); 
	//int			OnMainDiseaseSetfocus(); 
	//int			OnMainDiseaseKillfocus(); 
	int			OnMainDiseaseLoadData(); 
	int			OnMainDiseaseAddNew(); 
	int			OnDiseaseAccompaniedSelectChange(int nOldItemSel, int nNewItemSel); 
	int			OnDiseaseAccompaniedSelendok(); 
	//int			OnDiseaseAccompaniedSetfocus(); 
	//int			OnDiseaseAccompaniedKillfocus(); 
	int			OnDiseaseAccompaniedLoadData(); 
	int			OnDiseaseAccompaniedAddNew(); 
	//int			OnRelationDiseaseChange(); 
	//int			OnRelationDiseaseSetfocus(); 
	//int			OnRelationDiseaseKillfocus(); 
	int			OnRelationDiseaseCheckValue(); 
	//int			OnReasonChange(); 
	//int			OnReasonSetfocus(); 
	//int			OnReasonKillfocus(); 
	int			OnReasonCheckValue(); 
	int			OnUpdateSelect(); 
	int			OnSaveSelect(); 
	int			OnCancelSelect(); 
	//int			OnInWardNoChange(); 
	//int			OnInWardNoSetfocus(); 
	//int			OnInWardNoKillfocus(); 
	int			OnInWardNoCheckValue(); 
	int			OnIntroducePlaceSelectChange(int nOldItemSel, int nNewItemSel); 
	int			OnIntroducePlaceSelendok(); 
	//int			OnIntroducePlaceSetfocus(); 
	//int			OnIntroducePlaceKillfocus(); 
	int			OnIntroducePlaceLoadData(); 
	int			OnIntroducePlaceAddNew(); 
	//int			OnTotalTimeChange(); 
	//int			OnTotalTimeSetfocus(); 
	//int			OnTotalTimeKillfocus(); 
	int			OnTotalTimeCheckValue(); 
	CHMSWardAcceptance();
	~CHMSWardAcceptance();
	void OnCreateComponents();
	void OnInitializeComponents();
	void OnSetWindowEvents();
	void OnDoDataExchange(CDataExchange* pDX);
	void GetDataToScreen();
	void GetScreenToData();
	void SetDefaultValues();
	int OnAddHMSWardAcceptance(); 
	int OnEditHMSWardAcceptance(); 
	int OnDeleteHMSWardAcceptance(); 
	int OnSaveHMSWardAcceptance(); 
	int OnCancelHMSWardAcceptance(); 
};
#endif
