#ifndef CIVFHusbandInfoView_H
#define CIVFHusbandInfoView_H

//////////////////////////////////////////////////////////////////////////////////////////////////////////
//	Copyright © Viet Nam Medical Software Joint Stock Company. 2005-2012. 			
//	All rights reserved. 
//	This program is protected by Viet nam and international treaties.  
//	Unauthorized reproduction or distribution of this program, 
//	or any portion of it, may result in severe civil and criminal penalties, 
//	and will be prosecuted to the maximum extent possible under the law.
//	This file is a part of the GUI(Graphical User Interface) class library.
//	(c) 2006-2008 Hoang Van Hay, All rights reserved.
//	CONTACT INFORMATION:
//	Email  : hayhv@vimes.com.vn or hayhv@yahoo.com
//	Website: http://www.vimes.com.vn
/////////////////////////////////////////////////////////////////////////////////////////////////////////
//	Ban quyen cua Cong Ty Co Phan Phan Mem Y Te Viet Nam 2005-2012.
//	Do Cuc Ban Quyen, Bo VHTT nuoc Cong hoa xa hoi chu nghia Viet Nam cap.
//	Chuong trinh phan mem nay duoc Luat phap Viet Nam va quoc te bao ho.
//	San xuat, su dung hoac phan phoi trai phep toan bo hoac mot phan cua phan men nay se
//	chiu cac hinh phat va hinh su hoac dan su, co the len den muc toi da dung theo Luat qui dinh.
//	File nay la mot phan cua thu vien lap trinh(GUI). Ban quyen cua Hoang Van Hay. 2006-2008
//	THONG TIN LIEN HE:
//	Email  : hayhv@vimes.com.vn hoac hayhv@yahoo.com
//	Website: http://www.vimes.com.vn
//////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "GuiUtils.h"
#include "GuiView.h"
#include "DbField.h"
#include "ReportDocument.h"
//Thong tin nguoi chong dieu tri hiem muon

class CIVFHusbandInfoView : public CGuiView{
protected:

	void			GetLastResult();
public:
	CGuiGroupBox	m_wndTinhDichDo1;
	CGuiGroupBox	m_wndTinhDichDo2;
	CGuiLabel		m_wndDaTungCoConLabel;
	CGuiComboBox	m_wndDaTungCoCon;
	CGuiLabel		m_wndTienSuNoiKhoaLabel;
	CGuiComboBox	m_wndTienSuNoiKhoa;
	CGuiCheckBox	m_wndTieuDuong;
	CGuiCheckBox	m_wndQuaiBi;
	CGuiCheckBox	m_wndLao;
	CGuiLabel		m_wndKhacLabel;
	CGuiTextCtrl	m_wndKhac;
	CGuiLabel		m_wndTienSuNgoaiKhoaLabel;
	CGuiComboBox	m_wndTienSuNgoaiKhoa;
	CGuiCheckBox	m_wndThoatViBenDui;
	CGuiCheckBox	m_wndTinhHoanLacCho;
	CGuiCheckBox	m_wndGianTinhMachTinh;
	CGuiCheckBox	m_wndHepNieuDao;
	CGuiCheckBox	m_wndHypospadias;
	CGuiCheckBox	m_wndTranDichTH;
	CGuiLabel		m_wndNgoaiKhacLabel;
	CGuiTextCtrl	m_wndNgoaiKhac;
	CGuiLabel		m_wndTienSuSTDLabel;
	CGuiComboBox	m_wndTienSuSTD;
	CGuiCheckBox	m_wndLau;
	CGuiCheckBox	m_wndGiangMai;
	CGuiCheckBox	m_wndChlamydia;
	CGuiLabel		m_wndSTDKhacLabel;
	CGuiTextCtrl	m_wndSTDKhac;
	CGuiLabel		m_wndThoiQuen;
	CGuiLabel		m_wndHutThuocLabel;
	CGuiComboBox	m_wndHutThuoc;
	CGuiLabel		m_wndHTSoLuongLabel;
	CGuiTextCtrl	m_wndHTSoLuong;
	CGuiLabel		m_wndUongRuouLabel;
	CGuiComboBox	m_wndUongRuou;
	CGuiLabel		m_wndURSoLuongLabel;
	CGuiTextCtrl	m_wndURSoLuong;
	CGuiLabel		m_wndHoatDongTD;
	CGuiLabel		m_wndSongChungTXLabel;
	CGuiComboBox	m_wndSongChungTX;
	CGuiLabel		m_wndSoLanGiaoHopLabel;
	CGuiTextCtrl	m_wndSoLanGiaoHop;
	CGuiLabel		m_wndKham;
	CGuiLabel		m_wndTongQuat;
	CGuiLabel		m_wndCanNangLabel;
	CGuiTextCtrl	m_wndCanNang;
	CGuiLabel		m_wndChieuCaoLabel;
	CGuiTextCtrl	m_wndChieuCao;
	CGuiLabel		m_wndTinhTrangLong;
	CGuiCheckBox	m_wndNhieu;
	CGuiCheckBox	m_wndTrungBinh;
	CGuiCheckBox	m_wndIt;
	CGuiLabel		m_wndTimPhoiLabel;
	CGuiTextCtrl	m_wndTimPhoi;
	CGuiLabel		m_wndCoQuanSinhDuc;
	CGuiLabel		m_wndTinhHoan;
	CGuiLabel		m_wndTHPhaiLabel;
	CGuiTextCtrl	m_wndTHPhai;
	CGuiLabel		m_wndTHTraiLabel;
	CGuiTextCtrl	m_wndTHTrai;
	CGuiLabel		m_wndMaoTinh;
	CGuiLabel		m_wndMTPhaiLabel;
	CGuiTextCtrl	m_wndMTPhai;
	CGuiLabel		m_wndMTTraiLabel;
	CGuiTextCtrl	m_wndMTTrai;
	CGuiLabel		m_wndThungTinh;
	CGuiLabel		m_wndTTPhaiLabel;
	CGuiTextCtrl	m_wndTTPhai;
	CGuiLabel		m_wndTTTraiLabel;
	CGuiTextCtrl	m_wndTTTrai;
	CGuiLabel		m_wndDuongVatLabel;
	CGuiTextCtrl	m_wndDuongVat;
	CGuiLabel		m_wndBiuLabel;
	CGuiTextCtrl	m_wndBiu;
	CGuiLabel		m_wndXetNghiem;
	CGuiLabel		m_wndFSHLabel;
	CGuiTextCtrl	m_wndFSH;
	CGuiLabel		m_wndLHLabel;
	CGuiTextCtrl	m_wndLH;
	CGuiLabel		m_wndProlactinLabel;
	CGuiTextCtrl	m_wndProlactin;
	CGuiLabel		m_wndTestosteronLabel;
	CGuiTextCtrl	m_wndTestosteron;
	CGuiLabel		m_wndTheTichLabel;
	CGuiTextCtrl	m_wndTheTich;
	CGuiLabel		m_wndMatDoLabel;
	CGuiTextCtrl	m_wndMatDo;
	CGuiLabel		m_wndDiDong;
	CGuiLabel		m_wndTienToiLabel;
	CGuiTextCtrl	m_wndTienToi;
	CGuiLabel		m_wndTaiCho1Label;
	CGuiTextCtrl	m_wndTaiCho1;
	CGuiLabel		m_wndHinhDangBT1Label;
	CGuiTextCtrl	m_wndHinhDangBT1;
	CGuiLabel		m_wndKhac1Label;
	CGuiTextCtrl	m_wndKhac1;
	CGuiLabel		m_wndTheTich2Label;
	CGuiTextCtrl	m_wndTheTich2;
	CGuiLabel		m_wndMatDo2Label;
	CGuiTextCtrl	m_wndMatDo2;
	CGuiLabel		m_wndDiDong2;
	CGuiLabel		m_wndTienToi2Label;
	CGuiTextCtrl	m_wndTienToi2;
	CGuiLabel		m_wndTaiCho2Label;
	CGuiTextCtrl	m_wndTaiCho2;
	CGuiLabel		m_wndHinhDangBT2Label;
	CGuiTextCtrl	m_wndHinhDangBT2;
	CGuiLabel		m_wndKhac2Label;
	CGuiTextCtrl	m_wndKhac2;
	CGuiLabel		m_wndKetLuanLabel;
	CGuiTextCtrl	m_wndKetLuan;
	CGuiLabel		m_wndkhamchong;
	CGuiButton		m_wndEdit;
	CGuiButton		m_wndSave;
	CGuiButton		m_wndCancel;
	CString	m_szDaTungCoConKey;
	CString	m_szTienSuNoiKhoaKey;
	BOOL	m_bTieuDuong;
	BOOL	m_bQuaiBi;
	BOOL	m_bLao;
	CString	m_szKhac;
	CString	m_szTienSuNgoaiKhoaKey;
	BOOL	m_bThoatViBenDui;
	BOOL	m_bTinhHoanLacCho;
	BOOL	m_bGianTinhMachTinh;
	BOOL	m_bHepNieuDao;
	BOOL	m_bHypospadias;
	BOOL	m_bTranDichTH;
	CString	m_szNgoaiKhac;
	CString	m_szTienSuSTDKey;
	BOOL	m_bLau;
	BOOL	m_bGiangMai;
	BOOL	m_bChlamydia;
	CString	m_szSTDKhac;
	CString	m_szHutThuocKey;
	CString	m_szHTSoLuong;
	CString	m_szUongRuouKey;
	CString	m_szURSoLuong;
	CString	m_szSongChungTXKey;
	CString	m_szSoLanGiaoHop;
	CString	m_szCanNang;
	CString	m_szChieuCao;
	BOOL	m_bNhieu;
	BOOL	m_bTrungBinh;
	BOOL	m_bIt;
	CString	m_szTimPhoi;
	CString	m_szTHPhai;
	CString	m_szTHTrai;
	CString	m_szMTPhai;
	CString	m_szMTTrai;
	CString	m_szTTPhai;
	CString	m_szTTTrai;
	CString	m_szDuongVat;
	CString	m_szBiu;
	CString	m_szFSH;
	CString	m_szLH;
	CString	m_szProlactin;
	CString	m_szTestosteron;
	CString	m_szTheTich;
	CString	m_szMatDo;
	CString	m_szTienToi;
	CString	m_szTaiCho1;
	CString	m_szHinhDangBT1;
	CString	m_szKhac1;
	CString	m_szTheTich2;
	CString	m_szMatDo2;
	CString	m_szTienToi2;
	CString	m_szTaiCho2;
	CString	m_szHinhDangBT2;
	CString	m_szKhac2;
	CString	m_szKetLuan;
	long m_nDocumentNo;
	void			OnDaTungCoConSelectChange(int nOldItemSel, int nNewItemSel); 
	void			OnDaTungCoConSelendok(); 
	//void			OnDaTungCoConSetfocus(); 
	//void			OnDaTungCoConKillfocus(); 
	long			OnDaTungCoConLoadData(); 
	//void			OnDaTungCoConAddNew(); 
	void			OnTienSuNoiKhoaSelectChange(int nOldItemSel, int nNewItemSel); 
	void			OnTienSuNoiKhoaSelendok(); 
	//void			OnTienSuNoiKhoaSetfocus(); 
	//void			OnTienSuNoiKhoaKillfocus(); 
	long			OnTienSuNoiKhoaLoadData(); 
	//void			OnTienSuNoiKhoaAddNew(); 
	void			OnTieuDuongSelect(); 
	void			OnQuaiBiSelect(); 
	void			OnLaoSelect(); 
	//void			OnKhacChange(); 
	//void			OnKhacSetfocus(); 
	//void			OnKhacKillfocus(); 
	int			OnKhacCheckValue(); 
	void			OnTienSuNgoaiKhoaSelectChange(int nOldItemSel, int nNewItemSel); 
	void			OnTienSuNgoaiKhoaSelendok(); 
	//void			OnTienSuNgoaiKhoaSetfocus(); 
	//void			OnTienSuNgoaiKhoaKillfocus(); 
	long			OnTienSuNgoaiKhoaLoadData(); 
	//void			OnTienSuNgoaiKhoaAddNew(); 
	void			OnThoatViBenDuiSelect(); 
	void			OnTinhHoanLacChoSelect(); 
	void			OnGianTinhMachTinhSelect(); 
	void			OnHepNieuDaoSelect(); 
	void			OnHypospadiasSelect(); 
	void			OnTranDichTHSelect(); 
	//void			OnNgoaiKhacChange(); 
	//void			OnNgoaiKhacSetfocus(); 
	//void			OnNgoaiKhacKillfocus(); 
	int			OnNgoaiKhacCheckValue(); 
	void			OnTienSuSTDSelectChange(int nOldItemSel, int nNewItemSel); 
	void			OnTienSuSTDSelendok(); 
	//void			OnTienSuSTDSetfocus(); 
	//void			OnTienSuSTDKillfocus(); 
	long			OnTienSuSTDLoadData(); 
	//void			OnTienSuSTDAddNew(); 
	void			OnLauSelect(); 
	void			OnGiangMaiSelect(); 
	void			OnChlamydiaSelect(); 
	//void			OnSTDKhacChange(); 
	//void			OnSTDKhacSetfocus(); 
	//void			OnSTDKhacKillfocus(); 
	int			OnSTDKhacCheckValue(); 
	void			OnHutThuocSelectChange(int nOldItemSel, int nNewItemSel); 
	void			OnHutThuocSelendok(); 
	//void			OnHutThuocSetfocus(); 
	//void			OnHutThuocKillfocus(); 
	long			OnHutThuocLoadData(); 
	//void			OnHutThuocAddNew(); 
	//void			OnHTSoLuongChange(); 
	//void			OnHTSoLuongSetfocus(); 
	//void			OnHTSoLuongKillfocus(); 
	int			OnHTSoLuongCheckValue(); 
	void			OnUongRuouSelectChange(int nOldItemSel, int nNewItemSel); 
	void			OnUongRuouSelendok(); 
	//void			OnUongRuouSetfocus(); 
	//void			OnUongRuouKillfocus(); 
	long			OnUongRuouLoadData(); 
	//void			OnUongRuouAddNew(); 
	//void			OnURSoLuongChange(); 
	//void			OnURSoLuongSetfocus(); 
	//void			OnURSoLuongKillfocus(); 
	int			OnURSoLuongCheckValue(); 
	void			OnSongChungTXSelectChange(int nOldItemSel, int nNewItemSel); 
	void			OnSongChungTXSelendok(); 
	//void			OnSongChungTXSetfocus(); 
	//void			OnSongChungTXKillfocus(); 
	long			OnSongChungTXLoadData(); 
	//void			OnSongChungTXAddNew(); 
	//void			OnSoLanGiaoHopChange(); 
	//void			OnSoLanGiaoHopSetfocus(); 
	//void			OnSoLanGiaoHopKillfocus(); 
	int			OnSoLanGiaoHopCheckValue(); 
	//void			OnCanNangChange(); 
	//void			OnCanNangSetfocus(); 
	//void			OnCanNangKillfocus(); 
	int			OnCanNangCheckValue(); 
	//void			OnChieuCaoChange(); 
	//void			OnChieuCaoSetfocus(); 
	//void			OnChieuCaoKillfocus(); 
	int			OnChieuCaoCheckValue(); 
	void			OnNhieuSelect(); 
	void			OnTrungBinhSelect(); 
	void			OnItSelect(); 
	//void			OnTimPhoiChange(); 
	//void			OnTimPhoiSetfocus(); 
	//void			OnTimPhoiKillfocus(); 
	int			OnTimPhoiCheckValue(); 
	//void			OnTHPhaiChange(); 
	//void			OnTHPhaiSetfocus(); 
	//void			OnTHPhaiKillfocus(); 
	int			OnTHPhaiCheckValue(); 
	//void			OnTHTraiChange(); 
	//void			OnTHTraiSetfocus(); 
	//void			OnTHTraiKillfocus(); 
	int			OnTHTraiCheckValue(); 
	//void			OnMTPhaiChange(); 
	//void			OnMTPhaiSetfocus(); 
	//void			OnMTPhaiKillfocus(); 
	int			OnMTPhaiCheckValue(); 
	//void			OnMTTraiChange(); 
	//void			OnMTTraiSetfocus(); 
	//void			OnMTTraiKillfocus(); 
	int			OnMTTraiCheckValue(); 
	//void			OnTTPhaiChange(); 
	//void			OnTTPhaiSetfocus(); 
	//void			OnTTPhaiKillfocus(); 
	int			OnTTPhaiCheckValue(); 
	//void			OnTTTraiChange(); 
	//void			OnTTTraiSetfocus(); 
	//void			OnTTTraiKillfocus(); 
	int			OnTTTraiCheckValue(); 
	//void			OnDuongVatChange(); 
	//void			OnDuongVatSetfocus(); 
	//void			OnDuongVatKillfocus(); 
	int			OnDuongVatCheckValue(); 
	//void			OnBiuChange(); 
	//void			OnBiuSetfocus(); 
	//void			OnBiuKillfocus(); 
	int			OnBiuCheckValue(); 
	//void			OnFSHChange(); 
	//void			OnFSHSetfocus(); 
	//void			OnFSHKillfocus(); 
	int			OnFSHCheckValue(); 
	//void			OnLHChange(); 
	//void			OnLHSetfocus(); 
	//void			OnLHKillfocus(); 
	int			OnLHCheckValue(); 
	//void			OnProlactinChange(); 
	//void			OnProlactinSetfocus(); 
	//void			OnProlactinKillfocus(); 
	int			OnProlactinCheckValue(); 
	//void			OnTestosteronChange(); 
	//void			OnTestosteronSetfocus(); 
	//void			OnTestosteronKillfocus(); 
	int			OnTestosteronCheckValue(); 
	//void			OnTheTichChange(); 
	//void			OnTheTichSetfocus(); 
	//void			OnTheTichKillfocus(); 
	int			OnTheTichCheckValue(); 
	//void			OnMatDoChange(); 
	//void			OnMatDoSetfocus(); 
	//void			OnMatDoKillfocus(); 
	int			OnMatDoCheckValue(); 
	//void			OnTienToiChange(); 
	//void			OnTienToiSetfocus(); 
	//void			OnTienToiKillfocus(); 
	int			OnTienToiCheckValue(); 
	//void			OnTaiCho1Change(); 
	//void			OnTaiCho1Setfocus(); 
	//void			OnTaiCho1Killfocus(); 
	int			OnTaiCho1CheckValue(); 
	//void			OnHinhDangBT1Change(); 
	//void			OnHinhDangBT1Setfocus(); 
	//void			OnHinhDangBT1Killfocus(); 
	int			OnHinhDangBT1CheckValue(); 
	//void			OnKhac1Change(); 
	//void			OnKhac1Setfocus(); 
	//void			OnKhac1Killfocus(); 
	int			OnKhac1CheckValue(); 
	//void			OnTheTich2Change(); 
	//void			OnTheTich2Setfocus(); 
	//void			OnTheTich2Killfocus(); 
	int			OnTheTich2CheckValue(); 
	//void			OnMatDo2Change(); 
	//void			OnMatDo2Setfocus(); 
	//void			OnMatDo2Killfocus(); 
	int			OnMatDo2CheckValue(); 
	//void			OnTienToi2Change(); 
	//void			OnTienToi2Setfocus(); 
	//void			OnTienToi2Killfocus(); 
	int			OnTienToi2CheckValue(); 
	//void			OnTaiCho2Change(); 
	//void			OnTaiCho2Setfocus(); 
	//void			OnTaiCho2Killfocus(); 
	int			OnTaiCho2CheckValue(); 
	//void			OnHinhDangBT2Change(); 
	//void			OnHinhDangBT2Setfocus(); 
	//void			OnHinhDangBT2Killfocus(); 
	int			OnHinhDangBT2CheckValue(); 
	//void			OnKhac2Change(); 
	//void			OnKhac2Setfocus(); 
	//void			OnKhac2Killfocus(); 
	int			OnKhac2CheckValue(); 
	//void			OnKetLuanChange(); 
	//void			OnKetLuanSetfocus(); 
	//void			OnKetLuanKillfocus(); 
	int			OnKetLuanCheckValue(); 
	void			OnEditSelect(); 
	void			OnSaveSelect(); 
	void			OnCancelSelect(); 
	CIVFHusbandInfoView();
	~CIVFHusbandInfoView();
	void OnCreateComponents();
	void OnInitializeComponents();
	void OnSetWindowEvents();
	void OnDoDataExchange(CDataExchange* pDX);
	void UpdateJson(BOOL bSaveAndValidate);
	void GetDataToScreen();
	void GetScreenToData();
	void SetDefaultValues();
	int SetMode(int nMode);
	int OnAddCIVFHusbandInfoView(); 
	int OnEditCIVFHusbandInfoView(); 
	int OnDeleteCIVFHusbandInfoView(); 
	int OnSaveCIVFHusbandInfoView(); 
	int OnCancelCIVFHusbandInfoView(); 
	int OnCIVFHusbandInfoViewListLoadData(); 
	void OnPrint(CReport* pRpt=NULL, bool bShow=true);
};
#endif
