//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by HMSHospitalFee.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_HMSHospitalFeeTYPE          129
#define IDI_ICON1                       130
#define IDR_MENU1                       132
#define ID_FILE_INVOICESETUP            32771
#define ID_FILE_CHANGEPASSWORD          32773
#define ID_Menu32794                    32794
#define ID_GROUPSOFPATIENTSREPORTEDCOSTOFMEDICALINSURANCEOUTPATIENT_GENERALEXAMINATIONCOST25AREPORT 32808
#define ID_Menu                         32809
#define ID_THEGROUPOFPATIENTSREPORTINGCOSTHEALTHINSURANCEINPATIENT_GENERALTREATMENTCOST80AREPORT 32810
#define ID_Menu32813                    32813
#define ID_Menu32815                    32815
#define ID_BAOCAOCHIPHINGUONVONHEMACHITRA_BAOCAONGUONVONHEMACHITRABENHNHANNGOAITRU 32818
#define ID_BAOCAOCHIPHINGUONVONHEMACHITRA_BAOCAONGUONVONHEMACHITRABENHNHANNOITRU 32819
#define ID_GROUPSOFPATIENTSREPORTEDCOSTOFMEDICALINSURANCEOUTPATIENT_THONGKECPNGOAITRUTHEONHOMCHUYENMONKYTHUAT 32820
#define ID_Menu32821                    32821
#define ID_Menu32824                    32824
#define ID_THEGROUPOFPATIENTSREPORTINGCOSTHEALTHINSURANCEINPATIENT_GENERALTREATMENTOUTPATIENTCOSTREPORT 32825
#define ID_Menu32826                    32826
#define ID_Menu32827                    32827
#define ID_GROUPGENERALEXAMINATIONCOSTSOFPATIENTSSERVICE_DETAILEDLISTOFCOSTOBJECTSINPATIENTSERVICES 32828
#define ID_GROUPGENERALTREATMENTCOSTSORPATIENTSERVICE_DETAILEDLISTOFCOSTSOFPATIENTSINOUTPATIENTINPATIENT 32829
#define ID_Menu32833                    32833
#define ID_Menu32834                    32834
#define ID_FILE_REPORTS                 32841
#define ID_FILE_SETUPRECEIPTDATE        32842
#define ID_FILE_EDITFEERECEIVEDATE      32843
#define ID_FILE_KEEPTRACKOFPATIENTFEE   32844
#define ID_FILE_SUMMARYPAYMENTRECEIPT   32845
#define ID_FILE_SETTINGPAYMENTMETHOD    32846
#define ID_MenuFormFooterSetup          32848
#define ID_FILE_SETTINGS                32850
#define ID_SETTINGS_SMARTCARD           32856
#define ID_SETTINGS_SMARTCARD_ACTIVE    32857
#define ID_SETTINGS_SMARTCARD_CONFIG    32858
#define ID_SETTINGS_SMARTCARD_REGISTER  32859
#define ID_SETTINGS_SMARTCARD_UNREGISTER 32860
#define ID_Menu32849                    32861
#define ID_SETTINGS_MIENTHUOCUNGTHU     32862
#define ID_SETTINGS_DANHMUCCONGTY       32863
#define ID_SETTINGS_DANHMUCKHOA         32864

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        133
#define _APS_NEXT_COMMAND_VALUE         32865
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
