#pragma once

// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CMf5axctrl1 wrapper class
DWORD WINAPI MF5AXThreadFnc( LPVOID lpParam ) ;

class CMf5axctrl1 : public CWnd
{
protected:

	HANDLE m_hThread;
	BOOL	m_bTerminated;

	DECLARE_DYNCREATE(CMf5axctrl1)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x7230F7CD, 0x56BE, 0x48EB, { 0xAA, 0x93, 0x30, 0x24, 0xA4, 0x39, 0xE1, 0x29 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName, LPCTSTR lpszWindowName, DWORD dwStyle,
						const RECT& rect, CWnd* pParentWnd, UINT nID, 
						CCreateContext* pContext = NULL)
	{ 
		return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); 
	}

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle, const RECT& rect, CWnd* pParentWnd, 
				UINT nID, CFile* pPersist = NULL, BOOL bStorage = FALSE,
				BSTR bstrLicKey = NULL)
	{ 
		BOOL ret =  CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); 
		if(ret){
			DWORD dwThreadId;
			m_hThread = CreateThread( 
            NULL,              // default security attributes
            0,                 // use default stack size  
            MF5AXThreadFnc,          // thread function 
            this,             // argument to thread function 
            0,                 // use default creation flags 
            &dwThreadId);   // returns the thread identifier 
			m_bTerminated = FALSE;

		}
		return ret;
	}

	void RunLoop();

// Attributes
public:
enum
{
    comEventBreak = 1001,
    comEventFrame = 1004,
    comEventOverrun = 1006,
    comEventRxOver = 1008,
    comEventRxParity = 1009,
    comEventTxFull = 1010,
    comEventDCB = 1011,
    comEvSend = 1,
    comEvReceive = 2,
    comEvCTS = 3,
    comEvDSR = 4,
    comEvCD = 5,
    comEvRing = 6,
    comEvEOF = 7
}CommEventConstants;
enum
{
    comNone = 0,
    comXonXoff = 1,
    comRtsCts = 2,
    comBoth = 3,
    comDtrDsr = 4,
    comRS485 = 8
}HandshakeConstants;
enum
{
    comInputModeText = 0,
    comInputModeBinary = 1
}InputModeConstants;
enum
{
    gnetString = 0,
    gnetByteArray = 1,
    gnetByte = 2,
    gnetInteger = 3,
    gnetLong = 4
}GNetDataTypeConstants;
enum
{
    comEvRemove = 0,
    comEvPlugin = 1,
    comEvRemoveClosed = 2
}CommPortEventConstants;
enum
{
    COM1 = 1,
    COM2 = 2,
    COM3 = 3,
    COM4 = 4
}CommPortConstants;
enum
{
    KEY_A = 96,
    KEY_B = 97
}KeyTypeConstants;
enum
{
    MF_ULTRALIGHT = 17408,
    MF_1K = 1024,
    MF_4K = 512,
    MF_PROX = 1031,
    MF_DESFire = 17411
}CardClassConstants;
enum
{
    MF_NO_CARD = 0,
    MF_ULTRALIGHT_CL2 = 17408,
    MF_MINI_CL1 = 590848,
    MF_1K_CL1 = 525312,
    MF_4K_CL1 = 1573376,
    MF_1K_CL1_UID7 = 541696,
    MF_4K_CL1_UID7 = 1589760,
    MF_PLUS_CL1_2K = 1049600,
    MF_PLUS_CL1_4K = 1114624,
    MF_PLUS_CL2_2K = 1065984,
    MF_PLUS_CL2_4K = 1131008,
    MF_PLUS_CL1_SL3_2K = 2098176,
    MF_PLUS_CL1_SL3_4K = 2097664,
    MF_PLUS_CL2_SL3_2K = 2114560,
    MF_PLUS_CL2_SL3_4K = 2114048,
    MF_SMARTMX_CL1_1K = 16712719,
    MF_SMARTMX_CL1_4K = 16712207,
    MF_SMARTMX_CL2 = 16730127,
    MF_DESFIRE_CL2 = 2114563,
    MF_PRO_1K_CL1 = 2622464,
    MF_PRO_4K_CL1 = 3670528,
    MF_PRO_1K_CL2_UID7 = 2638848,
    MF_PRO_4K_CL2_UID7 = 3686912
}CardClassExConstants;
enum
{
    MF_CARD_PRESENT = 1,
    MF_CARD_REMOVE = 0
}CardEventConstants;
enum
{
    MF_INC = 193,
    MF_DEC = 192
}MifareCardOperateConstants;
enum
{
    DST_STATUS_STOP = 0,
    DST_STATUS_WORKING = 1,
    DST_STATUS_AUTO_SEL = 255
}DSTStatusConstants;


// Operations
public:

// _DMF5Ax

// Functions
//

	BOOL Query(short nFunction, VARIANT varParam)
	{
		BOOL result;
		static BYTE parms[] = VTS_I2 VTS_VARIANT ;
		InvokeHelper(0x1b, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms, nFunction, &varParam);
		return result;
	}
	CString EnumCommPort(short Index)
	{
		CString result;
		static BYTE parms[] = VTS_I2 ;
		InvokeHelper(0x1c, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms, Index);
		return result;
	}
	VARIANT GetReplyValue(long DataType)
	{
		VARIANT result;
		static BYTE parms[] = VTS_I4 ;
		InvokeHelper(0x1d, DISPATCH_METHOD, VT_VARIANT, (void*)&result, parms, DataType);
		return result;
	}
	short Polling(short nAddr)
	{
		short result;
		static BYTE parms[] = VTS_I2 ;
		InvokeHelper(0x1e, DISPATCH_METHOD, VT_I2, (void*)&result, parms, nAddr);
		return result;
	}
	CString GetVersion()
	{
		CString result;
		InvokeHelper(0x1f, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
		return result;
	}
	BOOL SetSlaveAddr(short nAddr)
	{
		BOOL result;
		static BYTE parms[] = VTS_I2 ;
		InvokeHelper(0x20, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms, nAddr);
		return result;
	}
	BOOL SetDateTime(DATE dtDateTime)
	{
		BOOL result;
		static BYTE parms[] = VTS_DATE ;
		InvokeHelper(0x21, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms, dtDateTime);
		return result;
	}
	BOOL QueryEx(short nFunction, long plParam, long lSize)
	{
		BOOL result;
		static BYTE parms[] = VTS_I2 VTS_I4 VTS_I4 ;
		InvokeHelper(0x22, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms, nFunction, plParam, lSize);
		return result;
	}
	BOOL GetRegister(long lRegAddr, short nRegLen)
	{
		BOOL result;
		static BYTE parms[] = VTS_I4 VTS_I2 ;
		InvokeHelper(0x23, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms, lRegAddr, nRegLen);
		return result;
	}
	BOOL GetRegisterEx(long lRegAddr, long plBuffer, short nRegLen)
	{
		BOOL result;
		static BYTE parms[] = VTS_I4 VTS_I4 VTS_I2 ;
		InvokeHelper(0x24, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms, lRegAddr, plBuffer, nRegLen);
		return result;
	}
	BOOL SetRegister(long lRegAddr, VARIANT varParam)
	{
		BOOL result;
		static BYTE parms[] = VTS_I4 VTS_VARIANT ;
		InvokeHelper(0x25, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms, lRegAddr, &varParam);
		return result;
	}
	BOOL SetRegisterEx(long lRegAddr, long plBuffer, short nRegLen)
	{
		BOOL result;
		static BYTE parms[] = VTS_I4 VTS_I4 VTS_I2 ;
		InvokeHelper(0x26, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms, lRegAddr, plBuffer, nRegLen);
		return result;
	}
	long GetRecordCount()
	{
		long result;
		InvokeHelper(0x27, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
		return result;
	}
	BOOL GetFirstRecord()
	{
		BOOL result;
		InvokeHelper(0x28, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
		return result;
	}
	BOOL GetFirstRecordEx(long plBuffer, short nSize)
	{
		BOOL result;
		static BYTE parms[] = VTS_I4 VTS_I2 ;
		InvokeHelper(0x29, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms, plBuffer, nSize);
		return result;
	}
	BOOL GetNextRecord()
	{
		BOOL result;
		InvokeHelper(0x2a, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
		return result;
	}
	BOOL GetNextRecordEx(long plBuffer, short nSize)
	{
		BOOL result;
		static BYTE parms[] = VTS_I4 VTS_I2 ;
		InvokeHelper(0x2b, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms, plBuffer, nSize);
		return result;
	}
	BOOL EraseRecords()
	{
		BOOL result;
		InvokeHelper(0x2c, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
		return result;
	}
	BOOL RecoverRecords()
	{
		BOOL result;
		InvokeHelper(0x2d, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
		return result;
	}
	BOOL AddRecord(VARIANT varRecord)
	{
		BOOL result;
		static BYTE parms[] = VTS_VARIANT ;
		InvokeHelper(0x2e, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms, &varRecord);
		return result;
	}
	BOOL AddRecordEx(long plBuffer, short nSize)
	{
		BOOL result;
		static BYTE parms[] = VTS_I4 VTS_I2 ;
		InvokeHelper(0x2f, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms, plBuffer, nSize);
		return result;
	}
	BOOL GoToISP()
	{
		BOOL result;
		InvokeHelper(0x30, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
		return result;
	}
	BOOL Reset()
	{
		BOOL result;
		InvokeHelper(0x31, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
		return result;
	}
	CString GNetErrorCodeStr()
	{
		CString result;
		InvokeHelper(0x32, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
		return result;
	}
	BOOL GetDateTime(DATE * pDateTime)
	{
		BOOL result;
		static BYTE parms[] = VTS_PDATE ;
		InvokeHelper(0x33, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms, pDateTime);
		return result;
	}
	long GetReplyByteCount()
	{
		long result;
		InvokeHelper(0x34, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
		return result;
	}
	BOOL GetReplyValueEx(long plBuffer, short nSize)
	{
		BOOL result;
		static BYTE parms[] = VTS_I4 VTS_I2 ;
		InvokeHelper(0x35, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms, plBuffer, nSize);
		return result;
	}
	short EnumCommPortNum(short Index)
	{
		short result;
		static BYTE parms[] = VTS_I2 ;
		InvokeHelper(0x36, DISPATCH_METHOD, VT_I2, (void*)&result, parms, Index);
		return result;
	}
	long NumOfPorts()
	{
		long result;
		InvokeHelper(0x37, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
		return result;
	}
	BOOL GetTimeAdjust(long * lAdjustValue)
	{
		BOOL result;
		static BYTE parms[] = VTS_PI4 ;
		InvokeHelper(0x38, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms, lAdjustValue);
		return result;
	}
	BOOL SetTimeAdjust(long lAdjustValue)
	{
		BOOL result;
		static BYTE parms[] = VTS_I4 ;
		InvokeHelper(0x39, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms, lAdjustValue);
		return result;
	}
	long mfAnticollision()
	{
		long result;
		InvokeHelper(0x3a, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
		return result;
	}
	long mfSelectCard(long lSerialNumber)
	{
		long result;
		static BYTE parms[] = VTS_I4 ;
		InvokeHelper(0x3b, DISPATCH_METHOD, VT_I4, (void*)&result, parms, lSerialNumber);
		return result;
	}
	BOOL mfSelectCardEx(long lSerialNumber)
	{
		BOOL result;
		static BYTE parms[] = VTS_I4 ;
		InvokeHelper(0x3c, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms, lSerialNumber);
		return result;
	}
	BOOL mfHalt()
	{
		BOOL result;
		InvokeHelper(0x3d, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
		return result;
	}
	BOOL mfAccessCondition(LPCTSTR szKeyA, LPCTSTR szKeyB, short iCB0, short iCB1, short iCB2, short iCB3)
	{
		BOOL result;
		static BYTE parms[] = VTS_BSTR VTS_BSTR VTS_I2 VTS_I2 VTS_I2 VTS_I2 ;
		InvokeHelper(0x3e, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms, szKeyA, szKeyB, iCB0, iCB1, iCB2, iCB3);
		return result;
	}
	BOOL mfAccessConditionEx(LPCTSTR szKeyA, LPCTSTR szKeyB, short iCB0, short iCB1, short iCB2, short iCB3, short iGPB)
	{
		BOOL result;
		static BYTE parms[] = VTS_BSTR VTS_BSTR VTS_I2 VTS_I2 VTS_I2 VTS_I2 VTS_I2 ;
		InvokeHelper(0x3f, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms, szKeyA, szKeyB, iCB0, iCB1, iCB2, iCB3, iGPB);
		return result;
	}
	BOOL mfSaveKey(long iKeyType, short iSector, LPCTSTR szKey)
	{
		BOOL result;
		static BYTE parms[] = VTS_I4 VTS_I2 VTS_BSTR ;
		InvokeHelper(0x40, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms, iKeyType, iSector, szKey);
		return result;
	}
	BOOL mfWriteHex(short iBlock, LPCTSTR szHexData)
	{
		BOOL result;
		static BYTE parms[] = VTS_I2 VTS_BSTR ;
		InvokeHelper(0x41, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms, iBlock, szHexData);
		return result;
	}
	BOOL mfAuthenticate(short iSector, long iKeyType, LPCTSTR szKey)
	{
		BOOL result;
		static BYTE parms[] = VTS_I2 VTS_I4 VTS_BSTR ;
		InvokeHelper(0x42, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms, iSector, iKeyType, szKey);
		return result;
	}
	long mfAnticollision2()
	{
		long result;
		InvokeHelper(0x43, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
		return result;
	}
	BOOL mfValueSet(short iBlock, long iOpt, long lValue)
	{
		BOOL result;
		static BYTE parms[] = VTS_I2 VTS_I4 VTS_I4 ;
		InvokeHelper(0x44, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms, iBlock, iOpt, lValue);
		return result;
	}
	long mfRequestEx(short Index)
	{
		long result;
		static BYTE parms[] = VTS_I2 ;
		InvokeHelper(0x45, DISPATCH_METHOD, VT_I4, (void*)&result, parms, Index);
		return result;
	}
	BOOL mfReadHex(short iBlock, BSTR * szHexData)
	{
		BOOL result;
		static BYTE parms[] = VTS_I2 VTS_PBSTR ;
		InvokeHelper(0x46, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms, iBlock, szHexData);
		return result;
	}
	BOOL mfRead(short iBlock, long pData, short iSize)
	{
		BOOL result;
		static BYTE parms[] = VTS_I2 VTS_I4 VTS_I2 ;
		InvokeHelper(0x47, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms, iBlock, pData, iSize);
		return result;
	}
	BOOL mfReadEx(long iKeyType, LPCTSTR szKey, short iSector, short iBlock, long pData, short iSize)
	{
		BOOL result;
		static BYTE parms[] = VTS_I4 VTS_BSTR VTS_I2 VTS_I2 VTS_I4 VTS_I2 ;
		InvokeHelper(0x48, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms, iKeyType, szKey, iSector, iBlock, pData, iSize);
		return result;
	}
	BOOL mfWrite(short iBlock, long pData, short iSize)
	{
		BOOL result;
		static BYTE parms[] = VTS_I2 VTS_I4 VTS_I2 ;
		InvokeHelper(0x49, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms, iBlock, pData, iSize);
		return result;
	}
	BOOL mfWriteEx(long iKeyType, LPCTSTR szKey, short iSector, short iBlock, long pData, short iSize)
	{
		BOOL result;
		static BYTE parms[] = VTS_I4 VTS_BSTR VTS_I2 VTS_I2 VTS_I4 VTS_I2 ;
		InvokeHelper(0x4a, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms, iKeyType, szKey, iSector, iBlock, pData, iSize);
		return result;
	}
	BOOL mfGetValue(short iBlock, long * lValue)
	{
		BOOL result;
		static BYTE parms[] = VTS_I2 VTS_PI4 ;
		InvokeHelper(0x4b, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms, iBlock, lValue);
		return result;
	}
	BOOL mfSetValue(short iBlock, long lValue)
	{
		BOOL result;
		static BYTE parms[] = VTS_I2 VTS_I4 ;
		InvokeHelper(0x4c, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms, iBlock, lValue);
		return result;
	}
	BOOL mfGetValueEx(long iKeyType, LPCTSTR szKey, short iSector, short iBlock, long * lValue)
	{
		BOOL result;
		static BYTE parms[] = VTS_I4 VTS_BSTR VTS_I2 VTS_I2 VTS_PI4 ;
		InvokeHelper(0x4d, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms, iKeyType, szKey, iSector, iBlock, lValue);
		return result;
	}
	BOOL mfSetValueEx(long iKeyType, LPCTSTR szKey, short iSector, short iBlock, long lValue)
	{
		BOOL result;
		static BYTE parms[] = VTS_I4 VTS_BSTR VTS_I2 VTS_I2 VTS_I4 ;
		InvokeHelper(0x4e, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms, iKeyType, szKey, iSector, iBlock, lValue);
		return result;
	}
	BOOL mfAddCardRecord(long pData, short iSize)
	{
		BOOL result;
		static BYTE parms[] = VTS_I4 VTS_I2 ;
		InvokeHelper(0x4f, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms, pData, iSize);
		return result;
	}
	BOOL mfGetCardRecord(short Index, long pData, short iSize)
	{
		BOOL result;
		static BYTE parms[] = VTS_I2 VTS_I4 VTS_I2 ;
		InvokeHelper(0x50, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms, Index, pData, iSize);
		return result;
	}
	long mfTime2Value(DATE dtTime)
	{
		long result;
		static BYTE parms[] = VTS_DATE ;
		InvokeHelper(0x51, DISPATCH_METHOD, VT_I4, (void*)&result, parms, dtTime);
		return result;
	}
	DATE mfValue2Time(long lTime)
	{
		DATE result;
		static BYTE parms[] = VTS_I4 ;
		InvokeHelper(0x52, DISPATCH_METHOD, VT_DATE, (void*)&result, parms, lTime);
		return result;
	}
	BOOL mfAutoMode(BOOL bEnable)
	{
		BOOL result;
		static BYTE parms[] = VTS_BOOL ;
		InvokeHelper(0x53, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms, bEnable);
		return result;
	}
	short madCRC8(long pData, long lSize)
	{
		short result;
		static BYTE parms[] = VTS_I4 VTS_I4 ;
		InvokeHelper(0x54, DISPATCH_METHOD, VT_I2, (void*)&result, parms, pData, lSize);
		return result;
	}
	BOOL mfGetAccessCondition(short * iCB0, short * iCB1, short * iCB2, short * iCB3, short * iGPB)
	{
		BOOL result;
		static BYTE parms[] = VTS_PI2 VTS_PI2 VTS_PI2 VTS_PI2 VTS_PI2 ;
		InvokeHelper(0x55, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms, iCB0, iCB1, iCB2, iCB3, iGPB);
		return result;
	}
	BOOL mfRFPower(long bPower)
	{
		BOOL result;
		static BYTE parms[] = VTS_I4 ;
		InvokeHelper(0x56, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms, bPower);
		return result;
	}
	long mfRequest()
	{
		long result;
		InvokeHelper(0x57, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
		return result;
	}
	BOOL mfValueSetEx(short iBlock, short iOpt, long lValue)
	{
		BOOL result;
		static BYTE parms[] = VTS_I2 VTS_I2 VTS_I4 ;
		InvokeHelper(0x58, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms, iBlock, iOpt, lValue);
		return result;
	}
	BOOL mfRestore(short iBlock)
	{
		BOOL result;
		static BYTE parms[] = VTS_I2 ;
		InvokeHelper(0x59, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms, iBlock);
		return result;
	}
	BOOL mfTransfer(short iBlock)
	{
		BOOL result;
		static BYTE parms[] = VTS_I2 ;
		InvokeHelper(0x5a, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms, iBlock);
		return result;
	}
	short mfGetSector(long lAID)
	{
		short result;
		static BYTE parms[] = VTS_I4 ;
		InvokeHelper(0x5b, DISPATCH_METHOD, VT_I2, (void*)&result, parms, lAID);
		return result;
	}
	long mfRequestAll()
	{
		long result;
		InvokeHelper(0x5c, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
		return result;
	}
	long mfRequestAllEx(short Index)
	{
		long result;
		static BYTE parms[] = VTS_I2 ;
		InvokeHelper(0x5d, DISPATCH_METHOD, VT_I4, (void*)&result, parms, Index);
		return result;
	}
	BOOL ReadControlBlock(LPCTSTR szType, long plBuffer, long lBufferSize)
	{
		BOOL result;
		static BYTE parms[] = VTS_BSTR VTS_I4 VTS_I4 ;
		InvokeHelper(0x5e, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms, szType, plBuffer, lBufferSize);
		return result;
	}
	BOOL WriteControlBlock(LPCTSTR szType, long plBuffer, long lBufferSize)
	{
		BOOL result;
		static BYTE parms[] = VTS_BSTR VTS_I4 VTS_I4 ;
		InvokeHelper(0x5f, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms, szType, plBuffer, lBufferSize);
		return result;
	}
	BOOL mfGetFirstRecord(long pData, short iSize)
	{
		BOOL result;
		static BYTE parms[] = VTS_I4 VTS_I2 ;
		InvokeHelper(0x60, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms, pData, iSize);
		return result;
	}
	BOOL mfGetNextRecord(long pData, short iSize)
	{
		BOOL result;
		static BYTE parms[] = VTS_I4 VTS_I2 ;
		InvokeHelper(0x61, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms, pData, iSize);
		return result;
	}
	BOOL mfAddRecord(long pData, short iSize)
	{
		BOOL result;
		static BYTE parms[] = VTS_I4 VTS_I2 ;
		InvokeHelper(0x62, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms, pData, iSize);
		return result;
	}
	long get_GNetRetry()
	{
		long result;
		InvokeHelper(0x64, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
		return result;
	}
	void put_GNetRetry(long newValue)
	{
		static BYTE parms[] = VTS_I4 ;
		InvokeHelper(0x64, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms, newValue);
	}
	long GetDSTStatus(DATE dtNow, long lStartMonth, long lStartWeekDay, long lStartHour, long lEndMonth, long lEndWeekDay, long lEndHour)
	{
		long result;
		static BYTE parms[] = VTS_DATE VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 ;
		InvokeHelper(0x63, DISPATCH_METHOD, VT_I4, (void*)&result, parms, dtNow, lStartMonth, lStartWeekDay, lStartHour, lEndMonth, lEndWeekDay, lEndHour);
		return result;
	}
	long get_mfCurrentClassEx()
	{
		long result;
		InvokeHelper(0x65, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
		return result;
	}
	long get_mfCardUIDSize()
	{
		long result;
		InvokeHelper(0x66, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
		return result;
	}
	CString get_mfAnticollisionHex()
	{
		CString result;
		InvokeHelper(0x67, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
		return result;
	}
	CString get_mfAnticollision2Hex()
	{
		CString result;
		InvokeHelper(0x68, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
		return result;
	}
	BOOL get_mfIsNextAnticollision()
	{
		BOOL result;
		InvokeHelper(0x69, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
		return result;
	}
	long get_mfSelectCardHex(LPCTSTR szSerialNumber)
	{
		long result;
		static BYTE parms[] = VTS_BSTR ;
		InvokeHelper(0x6a, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, parms, szSerialNumber);
		return result;
	}
	long get_mfSelectCardExHex(LPCTSTR szSerialNumber)
	{
		long result;
		static BYTE parms[] = VTS_BSTR ;
		InvokeHelper(0x6b, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, parms, szSerialNumber);
		return result;
	}
	BOOL get_mfAutoRequestToSelect()
	{
		BOOL result;
		InvokeHelper(0x6c, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
		return result;
	}
	void put_mfAutoRequestToSelect(long newValue)
	{
		static BYTE parms[] = VTS_I4 ;
		InvokeHelper(0x6c, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms, newValue);
	}

// Properties
//

long GetCommPort()
{
	long result;
	GetProperty(0x5, VT_I4, (void*)&result);
	return result;
}
void SetCommPort(long propVal)
{
	SetProperty(0x5, VT_I4, propVal);
}
BOOL GetDTREnable()
{
	BOOL result;
	GetProperty(0x6, VT_BOOL, (void*)&result);
	return result;
}
void SetDTREnable(BOOL propVal)
{
	SetProperty(0x6, VT_BOOL, propVal);
}
long GetHandshaking()
{
	long result;
	GetProperty(0x7, VT_I4, (void*)&result);
	return result;
}
void SetHandshaking(long propVal)
{
	SetProperty(0x7, VT_I4, propVal);
}
long GetInBufferSize()
{
	long result;
	GetProperty(0x1, VT_I4, (void*)&result);
	return result;
}
void SetInBufferSize(long propVal)
{
	SetProperty(0x1, VT_I4, propVal);
}
long GetCommID()
{
	long result;
	GetProperty(0x8, VT_I4, (void*)&result);
	return result;
}
void SetCommID(long propVal)
{
	SetProperty(0x8, VT_I4, propVal);
}
long GetCommEvent()
{
	long result;
	GetProperty(0x9, VT_I4, (void*)&result);
	return result;
}
void SetCommEvent(long propVal)
{
	SetProperty(0x9, VT_I4, propVal);
}
VARIANT GetInput()
{
	VARIANT result;
	GetProperty(0xa, VT_VARIANT, (void*)&result);
	return result;
}
void SetInput(VARIANT propVal)
{
	SetProperty(0xa, VT_VARIANT, propVal);
}
long GetInputLen()
{
	long result;
	GetProperty(0x2, VT_I4, (void*)&result);
	return result;
}
void SetInputLen(long propVal)
{
	SetProperty(0x2, VT_I4, propVal);
}
long GetInputMode()
{
	long result;
	GetProperty(0x3, VT_I4, (void*)&result);
	return result;
}
void SetInputMode(long propVal)
{
	SetProperty(0x3, VT_I4, propVal);
}
long GetOutBufferCount()
{
	long result;
	GetProperty(0xb, VT_I4, (void*)&result);
	return result;
}
void SetOutBufferCount(long propVal)
{
	SetProperty(0xb, VT_I4, propVal);
}
long GetOutBufferSize()
{
	long result;
	GetProperty(0x4, VT_I4, (void*)&result);
	return result;
}
void SetOutBufferSize(long propVal)
{
	SetProperty(0x4, VT_I4, propVal);
}
VARIANT GetOutput()
{
	VARIANT result;
	GetProperty(0xc, VT_VARIANT, (void*)&result);
	return result;
}
void SetOutput(VARIANT propVal)
{
	SetProperty(0xc, VT_VARIANT, propVal);
}
BOOL GetPortOpen()
{
	BOOL result;
	GetProperty(0xd, VT_BOOL, (void*)&result);
	return result;
}
void SetPortOpen(BOOL propVal)
{
	SetProperty(0xd, VT_BOOL, propVal);
}
BOOL GetRTSEnable()
{
	BOOL result;
	GetProperty(0xe, VT_BOOL, (void*)&result);
	return result;
}
void SetRTSEnable(BOOL propVal)
{
	SetProperty(0xe, VT_BOOL, propVal);
}
CString GetSettings()
{
	CString result;
	GetProperty(0xf, VT_BSTR, (void*)&result);
	return result;
}
void SetSettings(CString propVal)
{
	SetProperty(0xf, VT_BSTR, propVal);
}
BOOL GetCDHolding()
{
	BOOL result;
	GetProperty(0x10, VT_BOOL, (void*)&result);
	return result;
}
void SetCDHolding(BOOL propVal)
{
	SetProperty(0x10, VT_BOOL, propVal);
}
BOOL GetCTSHolding()
{
	BOOL result;
	GetProperty(0x11, VT_BOOL, (void*)&result);
	return result;
}
void SetCTSHolding(BOOL propVal)
{
	SetProperty(0x11, VT_BOOL, propVal);
}
BOOL GetDSRHolding()
{
	BOOL result;
	GetProperty(0x12, VT_BOOL, (void*)&result);
	return result;
}
void SetDSRHolding(BOOL propVal)
{
	SetProperty(0x12, VT_BOOL, propVal);
}
BOOL GetGNetPlusEvent()
{
	BOOL result;
	GetProperty(0x13, VT_BOOL, (void*)&result);
	return result;
}
void SetGNetPlusEvent(BOOL propVal)
{
	SetProperty(0x13, VT_BOOL, propVal);
}
long GetGNetErrorCode()
{
	long result;
	GetProperty(0x14, VT_I4, (void*)&result);
	return result;
}
void SetGNetErrorCode(long propVal)
{
	SetProperty(0x14, VT_I4, propVal);
}
long GetGNetTimeout()
{
	long result;
	GetProperty(0x15, VT_I4, (void*)&result);
	return result;
}
void SetGNetTimeout(long propVal)
{
	SetProperty(0x15, VT_I4, propVal);
}
short GetCurrentAddr()
{
	short result;
	GetProperty(0x16, VT_I2, (void*)&result);
	return result;
}
void SetCurrentAddr(short propVal)
{
	SetProperty(0x16, VT_I2, propVal);
}
long GetInBufferCount()
{
	long result;
	GetProperty(0x17, VT_I4, (void*)&result);
	return result;
}
void SetInBufferCount(long propVal)
{
	SetProperty(0x17, VT_I4, propVal);
}
BOOL GetBusy()
{
	BOOL result;
	GetProperty(0x18, VT_BOOL, (void*)&result);
	return result;
}
void SetBusy(BOOL propVal)
{
	SetProperty(0x18, VT_BOOL, propVal);
}
long GetmfCurrentClass()
{
	long result;
	GetProperty(0x19, VT_I4, (void*)&result);
	return result;
}
void SetmfCurrentClass(long propVal)
{
	SetProperty(0x19, VT_I4, propVal);
}
CString GetmfCurrentClassStr()
{
	CString result;
	GetProperty(0x1a, VT_BSTR, (void*)&result);
	return result;
}
void SetmfCurrentClassStr(CString propVal)
{
	SetProperty(0x1a, VT_BSTR, propVal);
}


DECLARE_MESSAGE_MAP()
afx_msg void OnDestroy();
virtual BOOL PreTranslateMessage(MSG* pMsg);
protected:
	virtual BOOL OnCommand(WPARAM wParam, LPARAM lParam);
};
