//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by VIMESHMSExamination.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_VIMESHMSExaminaTYPE         129
#define IDR_MENU1                       133
#define IDR_HTML1                       134
#define IDR_HTML2                       135
#define ID_FILE_CHANGEPASSWORD          32771
#define ID_FILE_SETUPPRESCRIPTIONLIST   32772
#define ID_COMMAND                      32773
#define ID_REPORT                       32774
#define ID_FILE_HELP                    32775
#define ID_FILE_REPORT                  32776
#define ID_FILE_COMMAND                 32777
#define ID_COMMAND_MEDICALCABINET       32778
#define ID_COMMAND_DRUGMATERIALORDERSHEET 32792
#define ID_COMMAND_SEARCHINFORMATIONPATIENT 32796
#define ID_Menu                         32799
#define ID_HOSPITALSTRANSFERREDREPORTS_LISTOFPATIENTTRANSFERREDFROMLOWERHOSPITALS 32801
#define ID_HOSPITALSTRANSFERREDREPORTS_GENERALPATIENTTRANSFERREDFROMLOWERHOSPITALS 32802
#define ID_HOSPITALSTRANSFERREDREPORTS_LISTOFPATIENTTRANSFERREDTOUPPERHOSPITALS 32803
#define ID_HOSPITALSTRANSFERREDREPORTS_GENERALPATIENTSTRANSFERREDTOUPPERHOSPITALS 32804
#define ID_ADMISSIONREPORTS_ADMISSIONPATIENTLISTREPORT 32806
#define ID_ADMISSIONREPORTS_GENERALADMISSIONREPORT 32807
#define ID_Menu32814                    32814
#define ID_EXAMINATIONBOOK_DETAILEXAMINATIONBOOK 32816
#define ID_GENERALSURGERYREPORT_PAYMENTOFALLOWANCESTABLESURGERY 32820
#define ID_GENERALSURGERYREPORT_SYNTHETICDRUGSANDMATERIALSUSEDINSURGERYPROCEDURE 32821
#define ID_REPORTFORMS                  32824
#define ID_COMMAND_TESTPROFILESETUP     32825
#define ID_COMMAND_TESTPROFILESETUP32826 32826
#define ID_Menu32827                    32827
#define ID_FINISH_DOCUMENT_ID           32828
#define ID_COMMAND_SETUPDIAGNOSTIC      32830
#define ID_FILE_RETURNDRUGORDERSHEET    32831
#define ID_FILE_SELECTWORKINGZONE       32832
#define ID_FILE_INVENTORYMANAGER        32833
#define ID_FILE_HEALTHEXAMLIST          32834
#define ID_SETTINGS_SETUPREPORTPARAMETER 32835
#define ID_SETTINGS_SETUPPARTNERLIST    32836
#define ID_SETTINGS_SMARTCARD           32837
#define ID_SETTINGS_SMARTCARD_ACTIVE    32842
#define ID_SETTINGS_SMARTCARD_CONFIG    32843
#define ID_SETTINGS_SMARTCARD_ESTABLISH 32844
#define ID_SETTINGS_SMARTCARD_UNREGISTER 32845
#define ID_FILE_ORDER                   32847
#define ID_ORDER_RETAILORDER            32848
#define ID_Menu32849                    32849
#define ID_FILE_BOSUNG_HOANTRAKHONGCOBENHNHAN 32852
#define ID_FILE_DAILYFOOD               32853
#define ID_SETTINGS_DOCTORINFO          32854
#define ID_COMMAND_RETURNDRUGORDER      32855
#define ID_SETTINGS_SETUPAPPOINTMENTA20 32856
#define ID_SETTINGS_EXAMSCHEDULE        32857
#define ID_FILE_OPERATIONSCHEDULES      32859
#define ID_SETTINGS_ORGDEPTINFOR        32860
#define ID_FILE_CHANGEDEPARTMENT        32862

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        136
#define _APS_NEXT_COMMAND_VALUE         32863
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
