#ifndef HMSSURGERYSCHEDULEINFODIALOG_H
#define HMSSURGERYSCHEDULEINFODIALOG_H

//////////////////////////////////////////////////////////////////////////////////////////////////////////
//	Copyright(C) Viet Nam Medical Software Join Stock Company. 2005-2010. 			
//	All rights reserved. 
//	This program is protected by Viet nam and international treaties.  
//	Unauthorized reproduction or distribution of this program, 
//	or any portion of it, may result in severe civil and criminal penalties, 
//	and will be prosecuted to the maximum extent possible under the law.
//	This file is a part of the GUI(Graphical User Interface) class library.
//	(c) 2006-2008 Hay Hoang Van, All rights reserved.
//	CONTACT INFORMATION:
//	Email  : hayhv@vimes.com.vn or hayhv@yahoo.com
//	Website: http://www.vimes.com.vn
/////////////////////////////////////////////////////////////////////////////////////////////////////////
//	Ban quyen cua Cong Ty Co Phan Phan Mem Y Te Viet Nam 2005-2010.
//	Do Cuc Ban Quyen, Bo VHTT nuoc Cong hoa xa hoi chu nghia Viet Nam cap.
//	Chuong trinh phan mem nay duoc Luat phap Viet Nam va quoc te bao ho.
//	San xuat, su dung hoac phan phoi trai phep toan bo hoac mot phan cua phan men nay se
//	chiu cac hinh phat va hinh su hoac dan su, co the len den muc toi da dung theo Luat qui dinh.
//	File nay la mot phan cua thu vien lap trinh(GUI). Ban quyen cua Hoang Van Hay. 2006-2008
//	THONG TIN LIEN HE:
//	Email  : hayhv@vimes.com.vn hoac hayhv@yahoo.com
//	Website: http://www.vimes.com.vn
//////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "GuiUtils.h"
#include "GuiDialog.h"
#include "DbField.h"
class CHMSSampleScheduleInfoDialog : public CGuiDialog
{
protected:
	CStringArray m_arrUsers;
	void ReplaceItem(CString szOldItem, CString szNewItem);
	long LoadData(CGuiComboBox* pComBo, CString szKey);
public:

	CGuiGroupBox	m_wndScheduleInfo;
	CGuiGroupBox	m_wndScheduleInfo1;
	CGuiComboBox	m_wndKhoa1;
	CGuiLabel		m_wndKhoa1label;
	CGuiLabel		m_wndCa1label;
	CGuiComboBox	m_wndCa1;
	CGuiLabel		m_wndStartDateLabel;
	CGuiDateCtrl	m_wndStartDate;
	CGuiLabel		m_wndEndDateLabel;
	CGuiTimeCtrl	m_wndStartTime;
	CGuiDateCtrl	m_wndEndDate;
	CGuiTimeCtrl	m_wndEndTime;
	CGuiLabel		m_wndCua1Label;
	CGuiComboBox	m_wndCua1;
	CGuiLabel		m_wndUser1Label;
	CGuiComboBox	m_wndUser1;
	CGuiComboBox	m_wndCua2;
	CGuiLabel		m_wndCua2Label;
	CGuiLabel		m_wndUser2Label;
	CGuiComboBox	m_wndUser2;
	CGuiLabel		m_wndCua3Label;
	CGuiComboBox	m_wndCua3;
	CGuiLabel		m_wndUser3Label;
	CGuiComboBox	m_wndUser3;
	CGuiLabel		m_wndCua4Label;
	CGuiComboBox	m_wndCua4;
	CGuiLabel		m_wndUser4Label;
	CGuiComboBox	m_wndUser4;
	CGuiLabel		m_wndCua5Label;
	CGuiComboBox	m_wndCua5;
	CGuiLabel		m_wndUser5Label;
	CGuiComboBox	m_wndUser5;
	CGuiLabel		m_wndCua6Label;
	CGuiComboBox	m_wndCua6;
	CGuiLabel		m_wndUser6Label;
	CGuiComboBox	m_wndUser6;
	CGuiLabel		m_wndCua7Label;
	CGuiComboBox	m_wndCua7;
	CGuiLabel		m_wndUser7Label;
	CGuiComboBox	m_wndUser7;
	CGuiLabel		m_wndCua8Label;
	CGuiComboBox	m_wndCua8;
	CGuiLabel		m_wndUser8Label;
	CGuiComboBox	m_wndUser8;
	CGuiLabel		m_wndCua9Label;
	CGuiComboBox	m_wndCua9;
	CGuiLabel		m_wndUser9Label;
	CGuiComboBox	m_wndUser9;
	CGuiLabel		m_wndCua10Label;
	CGuiComboBox	m_wndCua10;
	CGuiLabel		m_wndUser10Label;
	CGuiComboBox	m_wndUser10;
	CGuiLabel		m_wndKhoa2label;
	CGuiComboBox	m_wndKhoa2;
	CGuiLabel		m_wndCa2label;
	CGuiComboBox	m_wndCa2;
	CGuiLabel		m_wndStartDate1Label;
	CGuiDateCtrl	m_wndStartDate1;
	CGuiTimeCtrl	m_wndStartTime1;
	CGuiLabel		m_wndEndDate1Label;
	CGuiDateCtrl	m_wndEndDate1;
	CGuiTimeCtrl	m_wndEndTime1;
	CGuiLabel		m_wndCua11Label;
	CGuiComboBox	m_wndCua11;
	CGuiLabel		m_wndUser11Label;
	CGuiComboBox	m_wndUser11;
	CGuiLabel		m_wndCua12Label;
	CGuiComboBox	m_wndCua12;
	CGuiLabel		m_wndUser12Label;
	CGuiComboBox	m_wndUser12;
	CGuiLabel		m_wndCua13Label;
	CGuiComboBox	m_wndCua13;
	CGuiLabel		m_wndUser13Label;
	CGuiComboBox	m_wndUser13;
	CGuiLabel		m_wndCua14Label;
	CGuiComboBox	m_wndCua14;
	CGuiLabel		m_wndUser14Label;
	CGuiComboBox	m_wndUser14;
	CGuiLabel		m_wndCua15Label;
	CGuiComboBox	m_wndCua15;
	CGuiLabel		m_wndUser15Label;
	CGuiComboBox	m_wndUser15;
	CGuiLabel		m_wndCua16Label;
	CGuiComboBox	m_wndCua16;
	CGuiLabel		m_wndUser16Label;
	CGuiComboBox	m_wndUser16;
	CGuiLabel		m_wndCua17Label;
	CGuiComboBox	m_wndCua17;
	CGuiLabel		m_wndUser17Label;
	CGuiComboBox	m_wndUser17;
	CGuiLabel		m_wndCua18Label;
	CGuiComboBox	m_wndCua18;
	CGuiLabel		m_wndUser18Label;
	CGuiComboBox	m_wndUser18;
	CGuiLabel		m_wndCua19Label;
	CGuiComboBox	m_wndCua19;
	CGuiLabel		m_wndUser19Label;
	CGuiComboBox	m_wndUser19;
	CGuiLabel		m_wndCua20Label;
	CGuiComboBox	m_wndCua20;
	CGuiLabel		m_wndUser20Label;
	CGuiComboBox	m_wndUser20;
	CGuiCheckBox	m_wndLockSchedule;
	CGuiButton		m_wndUpdate;
	CGuiButton		m_wndClose;
	CString	m_szKhoa1Key;
	CString	m_szCa1Key;
	CString	m_szStartDate;
	CString	m_szStartTime;
	CString	m_szEndDate;
	CString	m_szEndTime;
	CString	m_szCua1Key;
	CString	m_szUser1Key;
	CString	m_szCua2Key;
	CString	m_szUser2Key;
	CString	m_szCua3Key;
	CString	m_szUser3Key;
	CString	m_szCua4Key;
	CString	m_szUser4Key;
	CString	m_szCua5Key;
	CString	m_szUser5Key;
	CString	m_szCua6Key;
	CString	m_szUser6Key;
	CString	m_szCua7Key;
	CString	m_szUser7Key;
	CString	m_szCua8Key;
	CString	m_szUser8Key;
	CString	m_szCua9Key;
	CString	m_szUser9Key;
	CString	m_szCua10Key;
	CString	m_szUser10Key;
	CString	m_szKhoa2Key;
	CString	m_szCa2Key;
	CString	m_szStartDate1;
	CString	m_szStartTime1;
	CString	m_szEndDate1;
	CString	m_szEndTime1;
	CString	m_szCua11Key;
	CString	m_szUser11Key;
	CString	m_szCua12Key;
	CString	m_szUser12Key;
	CString	m_szCua13Key;
	CString	m_szUser13Key;
	CString	m_szCua14Key;
	CString	m_szUser14Key;
	CString	m_szCua15Key;
	CString	m_szUser15Key;
	CString	m_szCua16Key;
	CString	m_szUser16Key;
	CString	m_szCua17Key;
	CString	m_szUser17Key;
	CString	m_szCua18Key;
	CString	m_szUser18Key;
	CString	m_szCua19Key;
	CString	m_szUser19Key;
	CString	m_szCua20Key;
	CString	m_szUser20Key;
	BOOL	m_bLockSchedule;
	CDbfMap m_hms_sample_scheduleTbl;
	CDbfMap m_hms_sample_schedule_lineTbl;
	long m_nIdx;
	COleDateTime m_DateTime;

	void			OnKhoa1SelectChange(int nOldItemSel, int nNewItemSel); 
	void			OnKhoa1Selendok(); 
	//void			OnKhoa1Setfocus(); 
	//void			OnKhoa1Killfocus(); 
	long			OnKhoa1LoadData(); 
	//void			OnKhoa1AddNew(); 
	void			OnCa1SelectChange(int nOldItemSel, int nNewItemSel); 
	void			OnCa1Selendok(); 
	//void			OnCa1Setfocus(); 
	//void			OnCa1Killfocus(); 
	long			OnCa1LoadData(); 
	//void			OnCa1AddNew(); 
	//void			OnStartDateChange(); 
	//void			OnStartDateSetfocus(); 
	//void			OnStartDateKillfocus(); 
	int			OnStartDateCheckValue(); 
	//void			OnStartTimeChange(); 
	//void			OnStartTimeSetfocus(); 
	//void			OnStartTimeKillfocus(); 
	int			OnStartTimeCheckValue(); 
	//void			OnEndDateChange(); 
	//void			OnEndDateSetfocus(); 
	//void			OnEndDateKillfocus(); 
	int			OnEndDateCheckValue(); 
	//void			OnEndTimeChange(); 
	//void			OnEndTimeSetfocus(); 
	//void			OnEndTimeKillfocus(); 
	int			OnEndTimeCheckValue(); 
	void			OnCua1SelectChange(int nOldItemSel, int nNewItemSel); 
	void			OnCua1Selendok(); 
	//void			OnCua1Setfocus(); 
	//void			OnCua1Killfocus(); 
	long			OnCua1LoadData(); 
	//void			OnCua1AddNew(); 
	void			OnUser1SelectChange(int nOldItemSel, int nNewItemSel); 
	void			OnUser1Selendok(); 
	//void			OnUser1Setfocus(); 
	//void			OnUser1Killfocus(); 
	long			OnUser1LoadData(); 
	//void			OnUser1AddNew(); 
	void			OnCua2SelectChange(int nOldItemSel, int nNewItemSel); 
	void			OnCua2Selendok(); 
	//void			OnCua2Setfocus(); 
	//void			OnCua2Killfocus(); 
	long			OnCua2LoadData(); 
	//void			OnCua2AddNew(); 
	void			OnUser2SelectChange(int nOldItemSel, int nNewItemSel); 
	void			OnUser2Selendok(); 
	//void			OnUser2Setfocus(); 
	//void			OnUser2Killfocus(); 
	long			OnUser2LoadData(); 
	//void			OnUser2AddNew(); 
	void			OnCua3SelectChange(int nOldItemSel, int nNewItemSel); 
	void			OnCua3Selendok(); 
	//void			OnCua3Setfocus(); 
	//void			OnCua3Killfocus(); 
	long			OnCua3LoadData(); 
	//void			OnCua3AddNew(); 
	void			OnUser3SelectChange(int nOldItemSel, int nNewItemSel); 
	void			OnUser3Selendok(); 
	//void			OnUser3Setfocus(); 
	//void			OnUser3Killfocus(); 
	long			OnUser3LoadData(); 
	//void			OnUser3AddNew(); 
	void			OnCua4SelectChange(int nOldItemSel, int nNewItemSel); 
	void			OnCua4Selendok(); 
	//void			OnCua4Setfocus(); 
	//void			OnCua4Killfocus(); 
	long			OnCua4LoadData(); 
	//void			OnCua4AddNew(); 
	void			OnUser4SelectChange(int nOldItemSel, int nNewItemSel); 
	void			OnUser4Selendok(); 
	//void			OnUser4Setfocus(); 
	//void			OnUser4Killfocus(); 
	long			OnUser4LoadData(); 
	//void			OnUser4AddNew(); 
	void			OnCua5SelectChange(int nOldItemSel, int nNewItemSel); 
	void			OnCua5Selendok(); 
	//void			OnCua5Setfocus(); 
	//void			OnCua5Killfocus(); 
	long			OnCua5LoadData(); 
	//void			OnCua5AddNew(); 
	void			OnUser5SelectChange(int nOldItemSel, int nNewItemSel); 
	void			OnUser5Selendok(); 
	//void			OnUser5Setfocus(); 
	//void			OnUser5Killfocus(); 
	long			OnUser5LoadData(); 
	//void			OnUser5AddNew(); 
	void			OnCua6SelectChange(int nOldItemSel, int nNewItemSel); 
	void			OnCua6Selendok(); 
	//void			OnCua6Setfocus(); 
	//void			OnCua6Killfocus(); 
	long			OnCua6LoadData(); 
	//void			OnCua6AddNew(); 
	void			OnUser6SelectChange(int nOldItemSel, int nNewItemSel); 
	void			OnUser6Selendok(); 
	//void			OnUser6Setfocus(); 
	//void			OnUser6Killfocus(); 
	long			OnUser6LoadData(); 
	//void			OnUser6AddNew(); 
	void			OnCua7SelectChange(int nOldItemSel, int nNewItemSel); 
	void			OnCua7Selendok(); 
	//void			OnCua7Setfocus(); 
	//void			OnCua7Killfocus(); 
	long			OnCua7LoadData(); 
	//void			OnCua7AddNew(); 
	void			OnUser7SelectChange(int nOldItemSel, int nNewItemSel); 
	void			OnUser7Selendok(); 
	//void			OnUser7Setfocus(); 
	//void			OnUser7Killfocus(); 
	long			OnUser7LoadData(); 
	//void			OnUser7AddNew(); 
	void			OnCua8SelectChange(int nOldItemSel, int nNewItemSel); 
	void			OnCua8Selendok(); 
	//void			OnCua8Setfocus(); 
	//void			OnCua8Killfocus(); 
	long			OnCua8LoadData(); 
	//void			OnCua8AddNew(); 
	void			OnUser8SelectChange(int nOldItemSel, int nNewItemSel); 
	void			OnUser8Selendok(); 
	//void			OnUser8Setfocus(); 
	//void			OnUser8Killfocus(); 
	long			OnUser8LoadData(); 
	//void			OnUser8AddNew(); 
	void			OnCua9SelectChange(int nOldItemSel, int nNewItemSel); 
	void			OnCua9Selendok(); 
	//void			OnCua9Setfocus(); 
	//void			OnCua9Killfocus(); 
	long			OnCua9LoadData(); 
	//void			OnCua9AddNew(); 
	void			OnUser9SelectChange(int nOldItemSel, int nNewItemSel); 
	void			OnUser9Selendok(); 
	//void			OnUser9Setfocus(); 
	//void			OnUser9Killfocus(); 
	long			OnUser9LoadData(); 
	//void			OnUser9AddNew(); 
	void			OnCua10SelectChange(int nOldItemSel, int nNewItemSel); 
	void			OnCua10Selendok(); 
	//void			OnCua10Setfocus(); 
	//void			OnCua10Killfocus(); 
	long			OnCua10LoadData(); 
	//void			OnCua10AddNew(); 
	void			OnUser10SelectChange(int nOldItemSel, int nNewItemSel); 
	void			OnUser10Selendok(); 
	//void			OnUser10Setfocus(); 
	//void			OnUser10Killfocus(); 
	long			OnUser10LoadData(); 
	//void			OnUser10AddNew(); 
	void			OnKhoa2SelectChange(int nOldItemSel, int nNewItemSel); 
	void			OnKhoa2Selendok(); 
	//void			OnKhoa2Setfocus(); 
	//void			OnKhoa2Killfocus(); 
	long			OnKhoa2LoadData(); 
	//void			OnKhoa2AddNew(); 
	void			OnCa2SelectChange(int nOldItemSel, int nNewItemSel); 
	void			OnCa2Selendok(); 
	//void			OnCa2Setfocus(); 
	//void			OnCa2Killfocus(); 
	long			OnCa2LoadData(); 
	//void			OnCa2AddNew(); 
	//void			OnStartDate1Change(); 
	//void			OnStartDate1Setfocus(); 
	//void			OnStartDate1Killfocus(); 
	int			OnStartDate1CheckValue(); 
	//void			OnStartTime1Change(); 
	//void			OnStartTime1Setfocus(); 
	//void			OnStartTime1Killfocus(); 
	int			OnStartTime1CheckValue(); 
	//void			OnEndDate1Change(); 
	//void			OnEndDate1Setfocus(); 
	//void			OnEndDate1Killfocus(); 
	int			OnEndDate1CheckValue(); 
	//void			OnEndTime1Change(); 
	//void			OnEndTime1Setfocus(); 
	//void			OnEndTime1Killfocus(); 
	int			OnEndTime1CheckValue(); 
	void			OnCua11SelectChange(int nOldItemSel, int nNewItemSel); 
	void			OnCua11Selendok(); 
	//void			OnCua11Setfocus(); 
	//void			OnCua11Killfocus(); 
	long			OnCua11LoadData(); 
	//void			OnCua11AddNew(); 
	void			OnUser11SelectChange(int nOldItemSel, int nNewItemSel); 
	void			OnUser11Selendok(); 
	//void			OnUser11Setfocus(); 
	//void			OnUser11Killfocus(); 
	long			OnUser11LoadData(); 
	//void			OnUser11AddNew(); 
	void			OnCua12SelectChange(int nOldItemSel, int nNewItemSel); 
	void			OnCua12Selendok(); 
	//void			OnCua12Setfocus(); 
	//void			OnCua12Killfocus(); 
	long			OnCua12LoadData(); 
	//void			OnCua12AddNew(); 
	void			OnUser12SelectChange(int nOldItemSel, int nNewItemSel); 
	void			OnUser12Selendok(); 
	//void			OnUser12Setfocus(); 
	//void			OnUser12Killfocus(); 
	long			OnUser12LoadData(); 
	//void			OnUser12AddNew(); 
	void			OnCua13SelectChange(int nOldItemSel, int nNewItemSel); 
	void			OnCua13Selendok(); 
	//void			OnCua13Setfocus(); 
	//void			OnCua13Killfocus(); 
	long			OnCua13LoadData(); 
	//void			OnCua13AddNew(); 
	void			OnUser13SelectChange(int nOldItemSel, int nNewItemSel); 
	void			OnUser13Selendok(); 
	//void			OnUser13Setfocus(); 
	//void			OnUser13Killfocus(); 
	long			OnUser13LoadData(); 
	//void			OnUser13AddNew(); 
	void			OnCua14SelectChange(int nOldItemSel, int nNewItemSel); 
	void			OnCua14Selendok(); 
	//void			OnCua14Setfocus(); 
	//void			OnCua14Killfocus(); 
	long			OnCua14LoadData(); 
	//void			OnCua14AddNew(); 
	void			OnUser14SelectChange(int nOldItemSel, int nNewItemSel); 
	void			OnUser14Selendok(); 
	//void			OnUser14Setfocus(); 
	//void			OnUser14Killfocus(); 
	long			OnUser14LoadData(); 
	//void			OnUser14AddNew(); 
	void			OnCua15SelectChange(int nOldItemSel, int nNewItemSel); 
	void			OnCua15Selendok(); 
	//void			OnCua15Setfocus(); 
	//void			OnCua15Killfocus(); 
	long			OnCua15LoadData(); 
	//void			OnCua15AddNew(); 
	void			OnUser15SelectChange(int nOldItemSel, int nNewItemSel); 
	void			OnUser15Selendok(); 
	//void			OnUser15Setfocus(); 
	//void			OnUser15Killfocus(); 
	long			OnUser15LoadData(); 
	//void			OnUser15AddNew(); 
	void			OnCua16SelectChange(int nOldItemSel, int nNewItemSel); 
	void			OnCua16Selendok(); 
	//void			OnCua16Setfocus(); 
	//void			OnCua16Killfocus(); 
	long			OnCua16LoadData(); 
	//void			OnCua16AddNew(); 
	void			OnUser16SelectChange(int nOldItemSel, int nNewItemSel); 
	void			OnUser16Selendok(); 
	//void			OnUser16Setfocus(); 
	//void			OnUser16Killfocus(); 
	long			OnUser16LoadData(); 
	//void			OnUser16AddNew(); 
	void			OnCua17SelectChange(int nOldItemSel, int nNewItemSel); 
	void			OnCua17Selendok(); 
	//void			OnCua17Setfocus(); 
	//void			OnCua17Killfocus(); 
	long			OnCua17LoadData(); 
	//void			OnCua17AddNew(); 
	void			OnUser17SelectChange(int nOldItemSel, int nNewItemSel); 
	void			OnUser17Selendok(); 
	//void			OnUser27Setfocus(); 
	//void			OnUser27Killfocus(); 
	long			OnUser17LoadData(); 
	//void			OnUser27AddNew(); 
	void			OnCua18SelectChange(int nOldItemSel, int nNewItemSel); 
	void			OnCua18Selendok(); 
	//void			OnCua18Setfocus(); 
	//void			OnCua18Killfocus(); 
	long			OnCua18LoadData(); 
	//void			OnCua18AddNew(); 
	void			OnUser18SelectChange(int nOldItemSel, int nNewItemSel); 
	void			OnUser18Selendok(); 
	//void			OnUser28Setfocus(); 
	//void			OnUser28Killfocus(); 
	long			OnUser18LoadData(); 
	//void			OnUser28AddNew(); 
	void			OnCua19SelectChange(int nOldItemSel, int nNewItemSel); 
	void			OnCua19Selendok(); 
	//void			OnCua19Setfocus(); 
	//void			OnCua19Killfocus(); 
	long			OnCua19LoadData(); 
	//void			OnCua19AddNew(); 
	void			OnUser19SelectChange(int nOldItemSel, int nNewItemSel); 
	void			OnUser19Selendok(); 
	//void			OnUser19Setfocus(); 
	//void			OnUser19Killfocus(); 
	long			OnUser19LoadData(); 
	//void			OnUser19AddNew(); 
	void			OnCua20SelectChange(int nOldItemSel, int nNewItemSel); 
	void			OnCua20Selendok(); 
	//void			OnCua20Setfocus(); 
	//void			OnCua20Killfocus(); 
	long			OnCua20LoadData(); 
	//void			OnCua20AddNew(); 
	void			OnUser20SelectChange(int nOldItemSel, int nNewItemSel); 
	void			OnUser20Selendok(); 
	//void			OnUser20Setfocus(); 
	//void			OnUser20Killfocus(); 
	long			OnUser20LoadData(); 
	//void			OnUser20AddNew(); 
	void			OnLockScheduleSelect(); 
	void			OnUpdateSelect(); 
	void			OnCloseSelect(); 
	CHMSSampleScheduleInfoDialog(CWnd *pParent);
	~CHMSSampleScheduleInfoDialog();
	void OnCreateComponents();
	void OnInitializeComponents();
	void OnSetWindowEvents();
	void OnDoDataExchange(CDataExchange* pDX);
	void UpdateJson(BOOL bSaveAndValidate);
	void GetDataToScreen();
	void GetScreenToData();
	void SetDefaultValues();
	int SetMode(int nMode);
	int OnAddCHMSSampleScheduleInfoDialog(); 
	int OnEditCHMSSampleScheduleInfoDialog(); 
	int OnDeleteCHMSSampleScheduleInfoDialog(); 
	int OnSaveCHMSSampleScheduleInfoDialog(); 
	int OnCancelCHMSSampleScheduleInfoDialog(); 
	int OnCHMSSampleScheduleInfoDialogListLoadData(); 
	COleDateTime GetToTime();
	COleDateTime GetFromTime();
	//CString GetSubject();
};
#endif