//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by VIMES.rc
//
#define IDC_POINTER                     104
#define IDC_ZOOM                        104
#define IDR_MAINFRAME                   128
#define IDR_MULTIPTYPE                  129
#define IDR_PREVIEW_PAGES               130
#define IDB_PAGES                       131
#define IDC_LANDSCAPE                   1000
#define IDC_ABOUTCTRL                   1000
#define IDB_TABITEMTOP                  1010
#define IDB_BITMAP1                     1017
#define IDD_PREVIEW                     1021
#define IDD_DIALOG                      1024
#define IDB_BITMAP2                     1031
#define IDD_DIALOG1                     1032
#define IDD_FORMVIEW                    1032
#define DIS_EN_Copyright                1042
#define IDS_VNU_Copyright               1043
#define IDS_VNA_Copyright               1044
#define IDI_ICON59                      1105
#define IDB_TASKDIALOGBAR               1140
#define IDB_BLUETASKDIALOGBARxx         1141
#define IDB_BLUETASKDIALOGBAR           1141
#define IDB_TASKDIALOGBARUPDOWN         1144
#define IDR_PRINTTOOLBAR                1146
#define IDB_BITMAP3                     1149
#define IDD_TOOLBARDIALOG               1156
#define IDD_DIALOGBAR                   1176
#define IDB_BITMAP6                     1182
#define IDB_BITMAP7                     1189
#define IDR_PNG1                        1196
#define IDB_BITMAP9                     1198
#define IDB_BITMAP10                    1220
#define IDB_BITMAP11                    1224
#define IDR_SYSTEMMENU                  1387
#define IDR_MESSAGEBOX_ERROR            1388
#define IDR_MESSAGEBOX_INFO             1389
#define IDR_MESSAGEBOX_QUESTION         1390
#define IDR_MESSAGEBOX_WARNING          1391
#define IDR_CLOSE_BUTTON                1392
#define IDR_MAX_BUTTON                  1393
#define IDR_MIN_BUTTON                  1394
#define IDR_COMBOBOX_BUTTON             1396
#define IDB_SPLASH                      1400
#define IDB_SERVICES_BACKGROUND         1401
#define IDB_PRINTER                     1402
#define IDB_PRINTER_EXPORT              1403
#define IDB_PAGE_PREV                   1405
#define IDB_FIT_PAGE_SIZE               1406
#define IDB_FIT_PAGE_WIDTH              1407
#define IDB_PAGE_FIRST                  1408
#define IDB_PAGE_LAST                   1409
#define IDB_PAGE_NEXT                   1410
#define IDB_ZOOM_OUT                    1411
#define IDB_ZOOM_IN                     1412
#define IDB_FIND                        1413
#define IDB_ZOOM_MENU                   1414
#define IDB_CLOSE                       1415
#define IDB_PREVIOUS                    1416
#define IDB_NEXT                        1417
#define IDI_VIMES_ICON                  1418
#define IDB_HOME                        1419
#define IDB_MENU_ITEM                   1420
#define IDR_ADD_BUTTON                  1422
#define IDR_ADDFILE_BUTTON              1423
#define IDR_ACCEPT_BUTTON               1424
#define IDR_CALENDAR_BUTTON             1425
#define IDR_CONFIGURE_BUTTON            1426
#define IDR_FOLDER_BUTTON               1427
#define IDR_EDIT_BUTTON                 1428
#define IDR_HELP_BUTTON                 1429
#define IDR_REFRESH_BUTTON              1430
#define IDR_APP_BUTTON                  1431
#define IDR_SEARCH_BUTTON               1432
#define IDR_FIND_BUTTON                 1433
#define IDR_DELETE_BUTTON               1434
#define IDR_CANCEL_BUTTON               1435
#define IDR_SAVE_BUTTON                 1436
#define IDR_PRINTPREVIEW_BUTTON         1437
#define IDR_PRINTER_BUTTON              1438
#define IDR_HOME_BUTTON                 1439
#define IDD_WAITINGDIALOG               1440
#define IDR_LOADING                     1444
#define IDR_ARROW_UP                    1446
#define IDR_ARROW_DOWN                  1447
#define IDR_ARROW_LEFT                  1448
#define IDR_ARROW_LEFT_DOWN             1449
#define IDR_ARROW_LEFT_UP               1450
#define IDR_ARROW_RIGHT                 1451
#define IDR_ARROW_RIGHT_DOWN            1452
#define IDR_ARROW_RIGHT_UP              1453
#define IDR_LAST_BUTTON                 1454
#define IDR_NEXT_BUTTON                 1455
#define IDR_PREV_BUTTON                 1456
#define IDR_COMPUTER                    1457
#define IDR_FIRST_BUTTON                1458
#define IDR_PNG7                        1459
#define IDR_FORWARD                     1459
#define IDR_ZOOM_OUT                    1460
#define IDR_ZOOM_IN                     1461
#define IDR_CLOSE_BUTTON2               1462
#define IDR_FIT_WITH                    1463
#define IDR_FIT_SIZE                    1464
#define IDR_EXPORT_XLS                  1465
#define IDR_FIT_PAGE_WITH               1466
#define IDR_FIT_PAGE_SIZE               1467
#define IDR_CALCULATOR_BUTTON           1469
#define IDR_CHECKBOX_TICK_NOR           1472
#define IDR_CHECKBOX_HOT                1473
#define IDR_CHECKBOX_NOR                1474
#define IDR_CHECKBOX_TICK_HOT           1475
#define IDR_RADIOBTN_TICK_NOR           1476
#define IDR_RADIOBTN_HOT                1477
#define IDR_RADIOBTN_NOR                1478
#define IDR_RADIOBTN_TICK_HOT           1479
#define IDR_PNG2                        1480
#define IDR_OPTION_BUTTON               1480
#define IDB_SIGNATURE_VALID             1481
#define IDR_SIGNATURE_BUTTON            1483
#define IDR_SIGNATURE_SEND_BUTTON       1484
#define IDR_PNG3                        1494
#define IDR_FONT2                       1496
#define IDR_FONT3                       1497
#define IDR_DATA1                       1498
#define IDR_ACCELERATOR1                1501
#define IDR_RC_DATA1                    1502
#define IDR_MENU_OPTION                 1503
#define ID_PRINTSETUP                   32771
#define ID_PRINT_SETUP                  32771
#define ID_PRINT                        32772
#define ID_SAVE                         32773
#define ID_PRINT_SAVEAS                 32773
#define ID_THUMBNAILS                   32774
#define ID_PREVPAGE                     32775
#define ID_PRINT_PREV                   32775
#define ID_NEXTPAGE                     32776
#define ID_PRINT_NEXT                   32776
#define ID_SIGNATURE                    32777
#define ID_ZOOMOUT                      32778
#define ID_PRINT_ZOOMOUT                32778
#define ID_ZOOMIN                       32779
#define ID_PRINT_ZOOMIN                 32779
#define ID_FIXEDWIDTH                   32780
#define ID_PAGE_FITWIDTH                32780
#define ID_FIXEDHEIGHT                  32781
#define ID_PAGE_FITPAGE                 32781
#define ID_PRINT_LAST                   32782
#define ID_PRINT_FIRST                  32783
#define ID_PRINT_FIND                   32784
#define ID_PRINT_ZOOMMENU               32786
#define ID_PRINT_CLOSE                  32787
#define ID_SIGNATURE_SEND               32788
#define ID_OPTION_FONT                  32791
#define ID_OPTION_DEFAULTDPI            32792
#define ID_OPTION_HIGHTDPIAWARE         32793
#define ID_OPTION_HIGH_DPIAWARE         32794
#define ID_OPTION_HIGH_DPI_AWARE        32795
#define ID_PAGES_1PAGE                  32971
#define ID_PAGES_2PAGES                 32972
#define ID_PAGES_3PAGES                 32973
#define ID_PAGES_4PAGES                 32974
#define ID_PAGES_6PAGES                 32975
#define ID_PAGES_9PAGES                 32976
#define ID_VIEW_PREVIEW                 32977
#define ID_PREVIEW_PAGES                58119
#define AFX_ID_PREVIEW_FIRST            58120
#define AFX_ID_PREVIEW_LAST             58123

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1504
#define _APS_NEXT_COMMAND_VALUE         32796
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           1000
#endif
#endif
