//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by VIMESAssetManagr.rc
//
#define IDI_ICON                        0
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_VIMESAssetManagTYPE         129
#define ID_FILE_SETUP                   32771
#define ID_SETUP_CATEGORYLIST           32772
#define ID_FILE_REPORT                  32773
#define ID_REPORT_ASSETLIST             32774
#define ID_SETUP_ACCOUNTLIST            32775
#define ID_SETUP_MANUFACTURERLIST       32776
#define ID_SETUP_ASSETTYPELIST          32777
#define ID_SETUP_VENDORLIST             32778
#define ID_SETUP_GENERALINFORMATION     32779
#define ID_REPORT_SUMMARYASSETVALUE     32780
#define ID_REPORT_FIXEDASSETCARD        32781
#define ID_REPORT_DETAILOFFIXEDASSET    32782
#define ID_REPORT_ASSETTRANSFERREDDEPARTMENTLIST 32783
#define ID_REPORT_FIXEDASSETGENERALINFORMATIONLIST 32784
#define ID_REPORT_FIXEDASSETGENERALINFORMATIONLISTBYRESOURCES 32785
#define ID_REPORT_DEPRECIATIONALLOCATIONTABLE 32786
#define ID_REPORT_DEPRECIATIONOFFIXEDASSETBYRESOURCES 32787
#define ID_FILE_TOOLS                   32788
#define ID_TOOLS_UPDATEACCUMULATEDDEPRECIATION 32789
#define ID_SETUP_EMPLOYEELIST           32790
#define ID_REPORT_INCREASEFIXEDASSET    32791
#define ID_REPORT_DECREASEFIXEDASSET    32792
#define ID_REPORT_DECREASEOFFIXEDASSET  32793
#define ID_SETUP_DEPARTMENTLIST         32794
#define ID_SETUP_INCREASON              32796
#define ID_SETUP_CONDITIONOFFIXEDASSET  32797
#define ID_SETUP_LISTSSETUP             32798
#define ID_REPORT_INVENTORYOFFIXEDASSET 32799
#define ID_COMMAND_RECORDEDINCREASEMANAGER 32801
#define ID_COMMAND_RECORDEDDECREASEMANAGER 32802
#define ID_SETUP_GROUPSETUP             32803
#define ID_REPORT_MACHINEINVENTORYRECORD 32804
#define ID_FILE_COMMAND                 32805
#define ID_REPORT_STATISTICMEDICALDEVICES 32806
#define ID_REPORT_TRANSFERTODEPT        32807
#define ID_SETUP_WAREHOUSESETUP         32808
#define ID_REPORT_ASSETGENERALINFORMATION 32809
#define ID_REPORT_ALLOCATIONDEPRECIATION 32810
#define ID_REPORT_ASSETSTATISTICSLIST   32811
#define ID_REPORT_ASSETCARDSTATISTICSLIST 32812
#define ID_REPORT_ASSETDETAILSTATISTICSLIST 32813
#define ID_REPORT_TOTALMEDICALDEVICE    32814
#define ID_REPORT_DETAILMEDICALDEVICE   32815
#define ID_REPORT                       32817

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         32818
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
